name: 'Gradle Version & Wrapper Update'
description: "Update Gradle URL, SHA256 checksum, and wrapper"
inputs:
  gradle_wrapper:
    description: 'The location of gradle-wrapper.jar'
    default: gradle/wrapper/gradle-wrapper.jar
  gradle_wrapper_properties:
    description: 'The location of gradle-wrapper.properties'
    default: gradle/wrapper/gradle-wrapper.properties
  gradlew:
    description: 'The location of the gradlew script to run'
    default: ./gradlew
outputs:
  version:
    description: 'The gradle version'
  download_url:
    description: 'The download URL'
  checksum:
    description: 'The checksum for the download'
  wrapper_checksum:
    description: 'The checksum for the wrapper'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gradle_wrapper }}
    - ${{ inputs.gradle_wrapper_properties }}
    - ${{ inputs.gradlew }}
